core/urls.py
from django.contrib import admin

from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy

from mainsite.views import index, register, edit, operation

from django.contrib.auth.views import (PasswordChangeView,
                                       PasswordResetView,
                                       PasswordResetConfirmView)


password_change_parms = dict(
    template_name='registration/password_change.html',
    success_url=reverse_lazy('login'),
)

password_reset_parms = dict(
    template_name='registration/password_reset.html',
    subject_template_name='registration/password_reset_subject.txt',
    email_template_name='registration/password_reset_email.html',
    html_email_template_name='registration/password_reset_html_email.html',
    success_url=reverse_lazy('login')
)

password_reset_confirm_parms = dict(
    template_name='registration/password_reset_confirm.html',
    post_reset_login=True,
    success_url=reverse_lazy('login')
)

urlpatterns = [
    path('', index, name='index'),
    path('operation/', operation, name='operation'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('todo/', include('todo.urls')),
    path('password-change/',
         PasswordChangeView.as_view(**password_change_parms),
         name='password_change'),
    path('password-reset/', PasswordResetView.as_view(**password_reset_parms),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(**password_reset_confirm_parms),
         name='password_reset_confirm'),
]

if not getattr(settings, "GCP", False):
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path

from . import views as v
app_name = 'todo'
urlpatterns = [
    path('', v.index, name='index'),
    path('new/', v.new, name='new'),
    path('delete/<int:pk>', v.delete, name='delete'),
    path('edit/<int:pk>', v.edit, name='edit'),
    path('show/<int:pk>', v.show, name='show'),
]

todo/models.py
import os
import time

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


def mainsite_directory_path(instance, filename):
    # return 'mainsite/{}/{}'.format(instance.id, filename)
    return os.path.join('todo', str(time.time()), filename)


class Category(models.Model):
    name = models.CharField('類別', max_length=10, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '類別'
        verbose_name_plural = '類別'


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT,
                                 verbose_name='類別')
    user_id = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='使用者',
                                blank=True, null=True, default=None)
    title = models.CharField('題目', max_length=64)
    body = models.TextField('文章', max_length=1000)
    pub_date = models.DateTimeField(default=timezone.now)
    image = models.ImageField('圖片', upload_to=mainsite_directory_path,
                              null=True, default=None)

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'

mainsite/forms.py
from django.forms import ModelForm, Form, BooleanField, EmailField, CharField
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.core.exceptions import ObjectDoesNotExist, ValidationError
User = get_user_model()

class UserModelForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class UserForm(UserCreationForm): # class <ClassName>(parent):
    email = EmailField(
        label="電子信箱",
    )
    first_name = CharField(label="名字",)
    last_name = CharField(label="姓氏",)

    def clean_email(self):
        '''
        Now you can know...
        The clean_<field_name> will be call before is_valid
        Your return data is final data to be save to the model's <field_name>
        '''
        email = self.cleaned_data.get("email") # Get data from `form` (means data maybe not in database)
        # test email is exists?
        user = User.objects.filter(email=email) # Get data from `model` (data has be saved in database)
        if user:
            raise ValidationError('此信箱已使用過')
        return email
        
    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name")
        field_classes = {'username': UsernameField}

todo/forms.py
from django.forms import ModelForm, Form, BooleanField

from .models import Post

class TodoModelForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['user_id']

    def save(self, user, commit=True):
        todo = super().save(commit=False)
        todo.user_id = user
        todo.save()

        self.save_m2m()

        return todo

class DeleteConfirmForm(Form):
    check = BooleanField(label='確定要刪除嗎？')

mainsite/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from .forms import UserForm, UserModelForm

# Create your views here.

def index(request):
    return render(request, 'mainsite/index.html')

def operation(request):
    return render(request, 'mainsite/operation.html')

def register(request):
    form = UserForm(request.POST or None)

    if form.is_valid():
        user = form.save()
        # print(user.email) Check user email is saved
        login(request, user)
        return redirect(reverse('index'))
        # render means templates folder, reverse means urls folder

    return render(request, 'registration/register.html', {'form': form})

def edit(request):
    form = UserModelForm(request.POST or None, instance=request.user)

    if form.is_valid():
        form.save()
        return redirect('index')

    return render(request, 'registration/edit.html', {'form':form})

todo/views.py
from django.shortcuts import render

from .models import Post
from .forms import TodoModelForm, DeleteConfirmForm
from .filters import PostFilter
from django.shortcuts import redirect, get_object_or_404

from django.contrib.auth.decorators import login_required


def index(request):
    _filter = PostFilter(
        request.GET or None,
        queryset=Post.objects.all()
    )
    return render(
        request, 'todo/index.html', {
            'todos': _filter.qs.all(),
            'filter': _filter
        }
    )


@login_required
def new(request):
    form = TodoModelForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        todo = form.save(request.user)  # Save without database
        todo.creator = request.user
        form.save(user=request.user)
        return redirect('todo:index')

    return render(request, 'todo/new.html', {
        'form': form
    })


@login_required
def delete(request, pk):
    form = DeleteConfirmForm(request.POST or None)

    if form.is_valid() and form.cleaned_data['check']:
        post = get_object_or_404(Post, pk=pk)
        post.delete()
        return redirect('todo:index')

    return render(request, 'todo/delete.html', {
        'form': form
    })


@login_required
def edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = TodoModelForm(
        request.POST or None,
        request.FILES or None,
        instance=post
    )

    if form.is_valid():
        post.creator = request.user
        form.save(request.user)
        return redirect('todo:index')

    return render(request, 'todo/edit.html', {
        'form': form
    })


def show(request, pk):
    post = get_object_or_404(Post, pk=pk)

    return render(request, 'todo/show.html', {
        'post':post
    })

templates/layout_index.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Plant Robot 知識網</title>

    {% load bootstrap4 %}

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    <style>
      .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
      }

      @media (min-width: 768px) {
          .bd-placeholder-img-lg {
              font-size: 3.5rem;
          }
      }

      .loading-text {
        font-family: Consolas, Monaco, monospace;
        display: inline-block;
        color: #227700;
        font-weight: bold;
        width: 12ch;
        white-space: nowrap;
        overflow: hidden;
        border-right: 2px solid;
      }

      .loading-text-ani {
        animation: loading-text-typing 3.5s steps(12),
        loading-text-caret 1s steps(1) infinite;
      }
      
      @keyframes loading-text-typing {
        from {
          width: 0;
        }
      }

      @keyframes loading-text-caret {
        50% {
          border-color: transparent;
        }
      }

    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <div class="nav-scroller py-1 mb-2">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'index' %}">Plant Robot</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}#about">關於我們</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'operation' %}">使用教學</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'todo:index' %}">植物小知識</a>
              </li>
            </ul>
            <span class="navbar-text">
              <ul class="nav navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'edit' %}">
                    {{user}}
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">
                    登出
                  </a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'register' %}">
                    註冊
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">
                    登入
                  </a>
                </li>
                {% endif %}
              </ul>
            </span>
          </div>
        </nav>

        {% block title %}{% endblock %}
        <div>{% block body %}{% endblock %}</div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous">
    </script>
    {% block end_script %}
    {% endblock %}
  </body>

</html>

templates/mainsite/index.html
{% extends 'layout_index.html' %}

{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block title %}
<div class="col">
  <div class="col-4" style="height:280px;">

  </div>
  <div class="col-4" style="position: absolute;top: 40%;left:10%;">
    <h1 class="loading-text loading-text-ani">Plant Robot</h1>
  </div>
  <div class="col-4" style="height:280px;">
  </div>
</div>

{% endblock %}

{% block body %}
<div style="background:rgba(102, 205, 170, 0.3);" id="about">
  <div class="row p-2">
    <div class="col-md-6 my-2" style="padding:25px">
      <div class="card">
        <img src="https://i.imgur.com/TItVY1s.png" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">使用教學</h5>
          <p class="card-text">不知道該如何使用 Plant Robot 或不知道有什麼功能嗎？</p>
          <a href="{% url 'operation' %}" class="btn btn-info">開始教學</a>
        </div>
      </div>
    </div>
    <div class="col-md-6 my-2" style="padding:25px">
      <div class="card">
        <img src="https://i.imgur.com/N6bonfU.png" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">植物小知識</h5>
          <p class="card-text">想知道更多關於植物的知識嗎？</p>
          <a href="{% url 'todo:index' %}" class="btn btn-info">閱讀知識</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block end_script %}
<script>
function loadText(){
  $('.loading-text').addClass("loading-text-ani");
  setTimeout(removeLoadText, 4000);
}
function removeLoadText(){
  $('.loading-text').removeClass("loading-text-ani");
  setTimeout(loadText, 1000);
}
setTimeout(removeLoadText, 6000);
</script>
{% endblock %}

templates/mainsite/operation.html
{% extends 'layout_index.html' %}

{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block body %}
<br>
  <div class="row" style="padding:15px">
  <div class="col-1">
      
    </div>
    <div class="col-10">
          <img src="https://i.imgur.com/TItVY1s.png" class="img-fluid" alt="Responsive image" style="max-width: 100%;">
    </div>
  <div class="col-1">
      
    </div>
  </div>
  <br>

  <br>
  <div class="row">
  <div class="col-1">
    </div>
    <div class="col-10">
      <div class="row">

    <div class="col-7">
      <img src="https://i.imgur.com/FUhU6zQ.jpg" class="img-fluid" alt="Responsive image" style="max-width: 100%;">
    </div>

    <div class="col-5">
    <br>
    <br>
      <p style="font-size:18px;">輸入任意字，即可開始設定裝置<p>
    </div>

  </div>
    </div>
  <div class="col-1">
    </div>
</div>
<br>
<br>
    <br>
<div class="row">
  <div class="col-1">
    </div>
    <div class="col-10">
      <div class="row">

    <div class="col-5" style="padding-right:0px;padding-left:8px">
    <br>
    <br>
      <p style="font-size:18px;">輸入Ｗebduino 裝置 ID<p>
    </div>

    <div class="col-7">
      <img src="https://i.imgur.com/t30Zhqi.jpg" class="img-fluid" alt="Responsive image" style="max-width: 100%;">
    </div>

  </div>
    </div>
  <div class="col-1">
    </div>
</div>
<br>
<br>
    <br>
<div class="row">
  <div class="col-1">
    </div>
    <div class="col-10">
      <div class="row">

    <div class="col-7">
      <img src="https://i.imgur.com/pbqlWBM.jpg" class="img-fluid" alt="Responsive image" style="max-width: 100%;">
    </div>

    <div class="col-5" style="vertical-align：middle">
    <br>
    <br>
      <p style="font-size:18px;">在下方按鈕中選擇您的植物<p>
    </div>

  </div>
    </div>
  <div class="col-1">
    </div>
</div>
<br>
<br>
    <br>
<div class="row">
  <div class="col-1">
    </div>
    <div class="col-10">
      <div class="row">

    <div class="col-5" style="vertical-align：middle">
    <br>
    <br>
      <p style="font-size:18px;">到這邊即完成設定了<p>
    </div>

    <div class="col-7">
      <img src="https://i.imgur.com/5TIaPqn.jpg" class="img-fluid" alt="Responsive image" style="max-width: 100%;">
    </div>
    
  </div>
    </div>
  <div class="col-1">
    </div>
</div>
<br>
<br>
    <br>
<div class="row">
  <div class="col-1">
    </div>
    <div class="col-10">
      <div class="row">

    <div class="col-7">
      <img src="https://i.imgur.com/fruAmEa.jpg" class="img-fluid" alt="Responsive image" style="max-width: 100%;">
    </div>

    <div class="col-5" style="vertical-align：middle">
    <br>
    <br>
      <p style="font-size:18px;">選擇『如何照顧我』觀看相關植物知識</p>
    </div>

  </div>
    </div>
  <div class="col-1">
    </div>
</div>
<br>
<br>
    <br>
<div class="row">
  <div class="col-1">
    </div>
    <div class="col-10">
      <div class="row">

    <div class="col-5" style="vertical-align：middle">
    <br>
    <br>
      <p style="font-size:18px;">點選連結即可進入知識網<p>
    </div>

<div class="col-7">
      <img src="https://i.imgur.com/BgDd4TQ.jpg" class="img-fluid" alt="Responsive image" style="max-width: 100%;">
    </div>

  </div>
    </div>
  <div class="col-1">
    </div>
</div>
<br>
<br>
    <br>
<div class="row">
  <div class="col-1">
    </div>
    <div class="col-10">
      <div class="row">

    <div class="col-7">
      <img src="https://i.imgur.com/2RwDy86.jpg" class="img-fluid" alt="Responsive image" style="max-width: 100%;">
    </div>

    <div class="col-5" style="vertical-align：middle">
    <br>
    <br>
      <p style="font-size:18px;">亦可選擇『重新選擇我』重新設定</p>
    </div>

  </div>
    </div>
  <div class="col-1">
    </div>
</div>
<br>

{% endblock %}

templates/todo/delete.html
{% extends 'layout_index.html' %}

{% load bootstrap4 %}

{% block body %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <br>
    <div style="padding:15px">
          <h3>刪除文章</h3>
    <br>
    <form action="" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      <br>
      {% buttons %}
      <button type="submit" class="btn btn-outline-danger float-right">
        刪除
      </button>
      {% endbuttons %}
    </form>
    </div>
  </div>
</div>
{% endblock %}

templates/todo/edit.html
{% extends 'layout_index.html' %}

{% load bootstrap4 %}

{% block body %}
<div class="row">
  <div class="col-md-8 offset-md-2 col-xs-12">
    <div style="padding:15px">
    <br>
    <h3>修改文章</h3>
    <br>
    <form action="" method="post" class="form" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
      <br>
      <div class="row float-right" style="padding:15px">
        <div class="col my-2">
          <button type="submit" class="btn btn-info">
            修 改
          </button>
        </div>
      </div>
      {% endbuttons %}
    </form>
    </div>
  </div>
</div>
{% endblock %}

templates/todo/index.html
{% extends 'layout_index.html' %}

{% block body %}
<div class="row">
  <div class="col-8 offset-2">
    <div class="row">
      <div class="col-12">
        <br>
        <h3>知識文章列表</h3>
        <br>

        <!-- Search and Filter -->
        <div class="form-row">
          <form class="form-inline">
            <div class="col-12">

              <div class="input-group">
                <!-- Search -->
                <input type="text" name="title" class="form-control" placeholder="搜尋文章" value={{request.GET.title}}>
                <!-- Filter -->
                <select class="custom-select" name="category">

                  <!-- No select -->
                  <option value="" {% if request.GET.category %}selected{% endif %}>所有類別</option>

                  <!-- Generate selection -->
                  {% for category in filter.filters.category.queryset %}
                  {% with category.pk|slugify as str_pk %}
                  <option value="{{category.pk}}" {% ifequal request.GET.category str_pk %}selected{% endifequal %}>{{category.name}}</option>
                  {% endwith %}
                  {% endfor %}

                </select>

                <div class="input-group-append">
                  <button class="btn btn-outline-info" type="submit">搜尋</button>
                </div>

              </div>
            </div>
          </form>
        </div>

        <!-- List -->
        <div class="list-group list-group-flush">
        <br>
          {% for todo in todos %}
          <a href="{% url 'todo:show' todo.pk %}" class="list-group-item list-group-item-action">{{todo.title}}</a>
          {% empty %}
          <a href="#" class="list-group-item list-group-item-action disabled">目前沒有文章 !</a>
          {% endfor %}
          <br>
        </div>

      </div>
    </div>
    {% if request.user.is_authenticated %}
    <div class="row float-right">
      <div class="col my-2">
        <a href="{% url 'todo:new' %}" class="btn btn-outline-success">新增文章</a>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/todo/new.html
{% extends 'layout_index.html' %}

{% load bootstrap4 %}

{% block body %}
<div class="row">
  <div class="col-md-8 offset-md-2 col-xs-12">
    <div style="padding:15px">
      <br>
    <h3>新增文章</h3>
    <br>
    <form action="" method="post" class="form"  enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
      <br>
      <div class="row float-right">
        <div class="col my-2">
          <button type="submit" class="btn btn-info">
            新 增
          </button>
        </div>
      </div>
      {% endbuttons %}
    </form>
    </div>
  </div>
</div>
{% endblock %}

templates/todo/show.html
{% extends 'layout_index.html' %}

{% load bootstrap4 %}

{% block body %}
<div class="col-md-8 offset-md-2">
  <br>
  <div class="row">
    <div class="col-12"><h2>{{post.title}}</h2></div>
  </div>

  <div class="row">
    <div class="col-12">
     <span class="float-left">{{ post.pub_date }}</span>
      <span class="float-left">&nbsp;&nbsp; #{{ post.category }}</span>
    </div>
  </div>

  <br>
  <div class="row">
    <div class="col-12">
      <img src="{{post.image.url}}" style="max-width: 100%;"/>
      <br><br>
      <p>
        {{ post.body | linebreaks }}
      </p>
    </div>
  </div>

  {% if request.user.is_authenticated %}
  <br>
  <div class="row float-right">
    <div class="col my-2">
      <a class="btn btn-outline-info" href="{% url 'todo:edit' post.pk %}" role="button">修 改</a>
      &nbsp&nbsp&nbsp
      <a class="btn btn-outline-danger" href="{% url 'todo:delete' post.pk %}" role="button">刪 除</a>
    </div>
  </div>


  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

  {% endif %}
  <br><br><br>
</div>
{% endblock %}